# Generated by Django 5.2.7 on 2025-11-02 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50)),
                ('start_location', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('camera_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('total_drowsies', models.IntegerField(default=0)),
                ('assigned_bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.bus')),
            ],
        ),
        migrations.CreateModel(
            name='DrowsinessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('current_location', models.CharField(max_length=100)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.driver')),
            ],
        ),
    ]
